language: node_js
node_js:
- '4.2'

env:
  global:
  - secure: KTUR8A8+xjEeysSU61UgiFj/GLy+vpoH0qXqLJd1AbIT49JpEx++BFfsEGYobQVfnGZZKsPF/AXXB258Jrd/cAH2dFjIn/1CV/CJaVE7n9BzRTKrFK/o2k1HEjVHWQt303wccgFjeNo/59emoX5OlqGqwEz0J/TlyMXd81UP1COYFs7nqNhRwKOsXoUZM9HOOHvM8IlSMatHJ7Efgqmku3GvOGancFgbCm+XySm3+yjg1qw02s2DHSzxkIdlkQGxXEQwfrLG7sH7MsuGl8Jj6vbt0LhMxZBryU5DUZUpp4mDb6b8JV9AxEbn40zhToOfMD3b2qH1JQaTYkY4viZJ74px4+Qo17QpjiPFtHx3XrXqSlOyOAu02+fU4id/I9oXnxCn+gszNGKN9lLvO7Ou8HigQG+d/uXrVCjExCuHA2oNcVsbnj4WLhpS31mUleVzInTHNeNEvJxXj46mxR1Hi0cSJtQKs4Oo8QmoRgERs8m30eogJWfF/2y1t2RTTKO1DWvcloImXyKGfAMXCCPwv2o5jozayD2DafadFCJc/B8Uf79fvnPGu9Z7qOSWpcoTykw+prmwPXSlmqZZz9v6i0shSZHksKubBdRJHUtkPcX8YS48Ye5770xPGodhtri9F1JLPGLR47Z7VPDmeQ8C8V1R4AjBwifmAqxoGvlj/uM=
  - secure: BxsAeajULPaRRmBGDnva693XGCaMYP9Yrox2y4ktVuIdpAJmPiRgjPTWGOwhATGImpzikQp/Rt4hyFpp1A3Om85ij/7pJx8r7qrgjiA0+bWHX9VUC9+lZqTKZAJHu9ckIklOCp8TUdxoPbAMcQI1zfe5EjcvpuGUK7pc00Fg605FRDNNpDpGiOQFPFVSqaLnBaOJYNqdVcovUKSCaVbQuSb/B/QdRCkBPLal6Grj4A2l6AupqtugjqkBsGBEpR9uK0u7/g1GhqyoxOH6UAegJinoJp9iZyIt+GxvX0WUKS5Qc5U6qHRpS+K5VgAmuLwWEulntU47nB9L2pnQ9ly2nD+ir3+zDWMNFh3Lt2ORkDQ3m59wqeccLz3VOK0BNYGYDZmHywcJHS6oayNNLe3IevWM0gtE69IYJqnZC+Iwrg0bRWRbKO0rkRbkxF7kFYFpfBZm6IQk/+TjUmg+qdEMq+y07CigsxPvP24v3iDMclKFVZriPo5cco56zonNBVtaXyYJkV/ePaBrBRf35fD0VZZAONO3NbM739DMi/f8SOlra6w6XTC/DxM4Qk+2v0fVJONAc0nLcLFgk04YMm39pcJlxQz9uPsb8xRGt6hlmBVr+9pZl0QlXJgtsHjlEWAFGC0aL+2+QLzF1Wzxdg8WSjULqXrMqmggHvK+q7KJRhs=
  - secure: tg6MYL1NfZGnrj6Qi76oPmIqelRIk6lXnHWZDrI53QHvCCv+qLCxXcExPDRBtidYqhS4NjKKU1hiHyNtFUXC8a/94U1iq9wqJ2wJyzksZ6YZ1f4mu1fSImknFK9aq2HCRy1jrJlU+NXN9qkyEiGtz20v+P6H/uJnphzvOZVdgn4nz2VA2aFwkqx7rMsBWjLCNbtIxKOmPEm/YHTqEkzqA+lPNpDtt+wq/K1tnqjWAPXR3+XZ02vaNN48p0gw/rEs8ViR8Q58rwaRC7IQS87whiM1w98Sgg0R6V3Vo1ZsWbHOTwwZIUhQ3Amn1OIcrTAm9cs3/i2aNzHgeEKWkO4UKEHKpiEeJa+nBNpf+gdJpvAnKJ/CyoqEjNmXwK+OYYAHWrGwGkbuliphwHcvongh6bnOghaPhDpUTSiKCfF+NrqGFPNGlYniedjHnQHo0BX1JmMDMwoBAZvOKLe4AiyBKne9OREsmdOKeGclrikM7hxMTN2B2IHR4kAALYegtX13g9g3JzYyxvY2PMp3sjTS3l+7HenE84ZtiPg96/8Zjrc+lDrKzpBebR0OpUXf/LMLvWL2WJSjSWs8pPwdglIyFLDjOlls5N5SNQLxEebnuYTrMjKpGCS0lmC8hY8wLPTTVGuDVVvOzkz08mCbhJFdlMGx7cymxjNSJlPxR5FBwgI=

before_deploy:
- sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
