language: node_js
node_js:
  - '4.2'

env:
  global:
  - secure: MLIopOHdBdyinnDJLfVldVfkK7ygvWGq2rrwp+dOShtsV9oC7dEFElIJavK4zdZfbdAk6HVyT9cZCBpcUb4VKaQY458Z+3EQYPLPtbegdidfGldeRj5QxAsDVGVzY9l039rq+t/ZQddb1W59YXKyDCxNzqAfDkkk/PZDQPvVsCGscu7H8Lx9jDJYEXF3WWZIZHuUz3iVJ4ej0MUQOUOkVDttLrohqPc/UnnyLSRtOIG/lSG17eJ7NjiUFDGJcV/KpG/olAmS0yAHOc+kKZkk0a2GgOQfU/ENdORdRvprsgMJRoeu3COuk2eNGYD/7+1XDqzc1AUy2JSf/Rtueo9edEzoeaTO/SxTS7g6v42vRfvIZnVf9MippsYAEpUOlTEaM01SsdGP/WME3iGM+/6sz1Y/YLGWz8pM50C0OK9lbVFGDCnHWaIwdiTqs6iu+Ieh1cA9JqW7dMHl39BO4Du7ciJk5/8QLIQ4kD5YfHHRkA3fx6NNw1+IltuIfjSmUY7/Bl3QzkyyL0MHndscrx7t8VKU1NsrTQdWPB+sLPRtEwKwx7vEgiWpFyiz+Au5yZ5vYEpjneM5Bhispmx7JaTYY53SRg7SlsE8xQOzN3eBAMyQAx/qgKxYyaS9FLAKjbohZnBeTYgyhG3TSUumsCjUzHp8CNcVO/HZw1p6p27I6vE=
  - secure: ecnhQHo2q1fOp0gZO2IQa3kCPHJinzabKQeOgRDc86ncpUHVwuZ+wpepZoDiMvZSCTzJd7UTHDnkd6zET07n30cnr1KDkEK+xRfV23hcVt5GRxL56zRsCLtgq8JTb/+7xxpLartXT1eQw8rCeKA0j1rwadZ1OiPdZZ84nn5r7l7qmJwMszjgRs2f2AuAeCWKWSH16FsPUyDJyZJMOwXKmKYGBf7bYaCXFMiq/4eCD/GUOS9l+hIynoakIxcLEKv95DbhKe/aM5frZ59YApPrWiq+BvEvjN8X9XnkxRtfNupxU3eS0pnrTfWNvWEZUafWvvs9MpBIoAGYvGQs3yCDDLDU/2WDs+3WxMEZIC7QvAWnDBp+AWxIpMsxAA6tR3ljM1LvjBE6M6zuNIspr8GvQNg2Hr7giSVx/VzvIdhabrrAKVgZ/rPt0mQWfGXUeLSbUkXsE7Qf/e4YwXyaHmyhdJeCm2w6i2yNLE8Twt1ubp1QnzkY6RHNG90vaF3xKuso6gzpJn5lt8IsZebPOfzp2YI8mBd/oyCQQ26ckoV6SGHVO88RUlZ6UsmK1CHocztDfiZymHo8dJF0rSF7ttfEsYFZXCmZOCgu1lAGcyCEqAbB1O+DWjq6wP6mt6Ie+BPLFe9XLMBjsv+lpmWhotRQ+CCjeETHofx0+hg5d0YsCbc=
  - secure: p9oWRFk0GyU50PA5P+pcZZzUATSTqjg3iCveRk9CAZZXRvLFkwF4I5ozE8kAyDd2IttfV694zjDTQButeLDi6AvpQs7piysPoUF9iJEmv+qxl4x2WOjTpoxQGs3S5qwoS389v4ZsVpuVarW0v1gJ3oDw6zKNuB4qG9S7v8O7p/NiIQwzY8cS1EPOaLQJ72BeTGHRIXVMohEghb1io9TuHs41vV9pwMTVtDUhdoeIZOcIkZEgjgYmBBeJfRaWiQt/vBfF54qx2McNnrfoOuSgC5WoOyVD081QHF5rgy4FdkH+Y2D6/T8r7yQhSBxw/tHL0424XqFCb7RlwxtDXm8Evic3O5ygS5vcI0zjv0Xo8I+rIHa+tPlUh7Yy081Jisf68mrXkwwQNiI3ZrSn96WfGmFIgX0d7H4cQ5PlBFAnN7NtKyZD/oF40ie24hay5dFvwJuCTAMyYWp7Y+yBblkyUDSd4cAkPyAOsKgUH4iNT9r9kjsAgrVPA+PQyFcnKqgsVL0ZRFpwR/hFheql7HFg1frxIyzVrGKVrsDYXk/FvcYHid6tNKx/K19F4aN2qlnKRaUCaIzHF6sbv7Ams+totWsd/Dg1O3SR2yayyY2/W9d1qbKSfREsLQ1Lj1JFk+QI6blnSz3LW+UOx4B38xNrd7CnyUYfBwrQH+mFf69/S7o=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
